
version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - '.env'
    environment:
      MYSQL_DATABASE: 'coffee'   
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: 'namnguyen'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
